all:
  children:
    eli_consoles: 
      hosts:
        plelico003.int.eli-np.ro:
        plelico006.int.eli-np.ro:
        10.16.2.28: ## plelico004
        10.16.2.25: ## plelico001
        10.16.2.29: ## plelico005
        10.16.2.6:  ## plelico007


#        pldanteco101.lnf.infn.it:
    
    eli_lnf_consoles: 
      hosts:
        plelico002.lnf.infn.it:
        

