all:
  children:
    eli_consoles: 
      hosts:
        plelico003.int.eli-np.ro:
        plelico006.int.eli-np.ro:
        plelico004.int.eli-np.ro: ## plelico004
        plelico001.int.eli-np.ro: ## plelico001
        plelico005.int.eli-np.ro: ## plelico005
        plelico007.int.eli-np.ro: ## plelico007
        ##10.16.2.6:  ## plelico007


#        pldanteco101.lnf.infn.it:
    
    eli_lnf_consoles: 
      hosts:
        plelico002.lnf.infn.it:
        

